### ISSUE TITLE
HowTo frame bug/style issue

### ISSUE THREAD

**Issue by loganortega** [ucsb-cs56-projects/cs56-games-maze#23]
When the How To frame is opened (accessed from 
the How To Button) the frame does not open properly.
No text is visible. The user has to resize the frame ("drag
open") to see the actual dialog. Even then, the default 
scroller placement is at the bottom so the user has to 
scroll up to find How To instructions. The vertical size of 
the JTextArea is too large. Perhaps, this would be better
implemented with a JDialog 
~estimated 100

**Comment by asyung** [comment]
F16 OK (150 pts)

**Comment by CDLlo** [comment]
This has been completed prior to me picking up the repo. closing.
