### ISSUE TITLE
Add arrow keys functionality 

### ISSUE THREAD

**Issue by loganortega** [UCSB-CS56-Projects/cs56-games-maze#24]
While using the "w," "a," "s" and "d" keys may be 
familiar to seasoned gamers, these key choices may 
seem foreign and may unnecessarily complicate 
gameplay for beginning gamers. A nice functionality 
to have for these types of players is to allow the arrow
keys to control player motion during gameplay.
~estimated 200

**Comment by asyung** [comment]
F16 OK (100 pts)
