### ISSUE TITLE
New game mode - 2Players

### ISSUE THREAD

**Issue by andrevv10** [UCSB-CS56-Projects/cs56-games-maze#50]
Create a new game mode in which both players play on the same map. This second player must be a different color and a new mechanic must be created such that the system can record which player won.

300 Points

**Comment by omeedrabani** [comment]
Approved: 300 pts

**Comment by omeedrabani** [comment]
W16 OK

**Comment by asyung** [comment]
F16 OK (300 pts)

**Comment by asyung** [comment]
Closing because issue already existing
